options:
  watering-multiplier: 1.15
  fertilisation-multiplier: 1.3
  water-bucket-max-usages: 4

fertilizer:
  material: COCOA_BEANS
  customModelData: 2810301  
  
messages:
  watered: "&bPolíčko už je zaliate."
  on-watering: "&aZalial si políčko."
  fertilized: "&bPolíčko už je pohnojené."
  on-fertilisation: "&aPohnojil si políčko."
  harvest-bad-tool: "&cToto nepôjde."

crops:
  WHEAT:
    harvest-tools:
      stone-sword:
        type: STONE_SWORD
        customModelData: 2810301
      iron-sword:
        type: IRON_SWORD
        customModelData: 2810302
  CARROTS:
    harvest-tools:
     STONE_SHOWEL:
        type: STONE_SHOWEL
     IRON_SHOWEL:
        type: IRON_SHOWEL
  POTATOES:
    harvest-tools:
     STONE_SHOWEL:
        type: STONE_SHOWEL
     IRON_SHOWEL:
        type: IRON_SHOWEL
  MELON:
    harvest-tools:
      iron-sword:
        type: IRON_SWORD
  PUMPKIN:
    harvest-tools:
      iron-sword:
        type: IRON_SWORD
  BEETROOTS:
    harvest-tools:
      iron-sword:
        type: IRON_SWORD

drops:
  - WHEAT
  - CARROT
  - POTATO
  - MELON_SLICE
  - PUMPKIN
  - BEETROOT
  
need-water:
  - WHEAT
  - CARROTS
  - POTATOES
  - MELON_STEM
  - ATTACHED_MELON_STEM
  - PUMPKIN_STEM
  - ATTACHED_PUMPKIN_STEM
  - BEETROOTS
  
need-fertilizer:
  - WHEAT
  - CARROTS
  - POTATOES
  - MELON_STEM
  - ATTACHED_MELON_STEM
  - PUMPKIN_STEM
  - ATTACHED_PUMPKIN_STEM
  - BEETROOTS