options:
  watering-multiplier: 1.15
  fertilisation-multiplier: 1.3
  water-bucket-max-usages: 999

fertilizer:
  material: COCOA_BEANS
  
messages:
  watered: "&bPolíčko už je zaliate."
  on-watering: "&aZalial si políčko."
  fertilized: "&bPolíčko už je pohnojené."
  on-fertilisation: "&aPohnojil si políčko."

crops:
  - WHEAT
  - CARROTS
  - POTATOES
  - MELON
  - PUMPKIN
  - BEETROOTS
  - SUGAR_CANE
  
need-wather:
  - WHEAT
  - CARROTS
  - POTATOES
  - MELON_STEM
  - ATTACHED_MELON_STEM
  - PUMPKIN_STEM
  - ATTACHED_PUMPKIN_STEM
  - BEETROOTS
  
need-fertilizer:
  - WHEAT
  - CARROTS
  - POTATOES
  - MELON_STEM
  - ATTACHED_MELON_STEM
  - PUMPKIN_STEM
  - ATTACHED_PUMPKIN_STEM
  - BEETROOTS