options:
  watering-multiplier: 1.15
  fertilisation-multiplier: 1.3

crops:
  - WHEAT
  - CARROTS
  - POTATOES
  - MELON
  - PUMPKIN
  - BEETROOTS
  - SUGAR_CANE
  
need_wather:
  - WHEAT
  - CARROTS
  - POTATOES
  - MELON_STEM
  - PUMPKIN_STEM
  - BEETROOTS
