options:
  watering-multiplier: 1.15
  fertilisation-multiplier: 1.3
  water-bucket-max-usages: 4

fertilizer:
  basic:
    material: COCOA_BEANS
    # customModelData: 2810401
      
messages:
  watered: "&bPolíčko už je zaliate."
  on-watering: "&aZalial si políčko."
  fertilized: "&bPolíčko už je pohnojené."
  on-fertilisation: "&aPohnojil si políčko."
  harvest: "&bZbieraš..."
  harvest-bad-tool: "&cToto nepôjde."

crops:
  WHEAT:
    harvest-time: 3
    harvest-tools:
      stone-scythe:
        type: STONE_SWORD
        customModelData: 2810301
  CARROTS:
    harvest-time: 3
    harvest-tools:
      STONE_SHOVEL:
        type: STONE_SHOVEL
      IRON_SHOVEL:
        type: IRON_SHOVEL
  POTATOES:
    harvest-time: 3
    harvest-tools:
      STONE_SHOVEL:
        type: STONE_SHOVEL
      IRON_SHOVEL:
        type: IRON_SHOVEL
      bone:
        type: BONE
  MELON:
    harvest-time: 3  
    harvest-tools:
      stone-scythe:
        type: STONE_SWORD
        customModelData: 2810301
      iron-scythe:
        type: IRON_SWORD
      bone:
        type: BONE
  PUMPKIN:
    harvest-time: 3 
    harvest-tools:
      stone-scythe:
        type: STONE_SWORD
        customModelData: 2810301
      iron-scythe:
        type: IRON_SWORD
      bone:
        type: BONE
  BEETROOTS:
    harvest-time: 3 
    harvest-tools:
      bone:
        type: BONE

drops:
  - WHEAT
  - CARROT
  - POTATO
  - MELON_SLICE
  - PUMPKIN
  - BEETROOT
  
need-water:
  - WHEAT
  - CARROTS
  - POTATOES
  - MELON_STEM
  - ATTACHED_MELON_STEM
  - PUMPKIN_STEM
  - ATTACHED_PUMPKIN_STEM
  - BEETROOTS
  
need-fertilizer:
  - WHEAT
  - CARROTS
  - POTATOES
  - MELON_STEM
  - ATTACHED_MELON_STEM
  - PUMPKIN_STEM
  - ATTACHED_PUMPKIN_STEM
  - BEETROOTS