options:
  watering-multiplier: 1.15
  fertilisation-multiplier: 1.3
  water-bucket-max-usages: 4
  
messages:
  watered: "&bPolíčko už je zaliate."
  on-watering: "&aZalial si políčko."
  

crops:
  - WHEAT
  - CARROTS
  - POTATOES
  - MELON
  - PUMPKIN
  - BEETROOTS
  - SUGAR_CANE
  
need_wather:
  - WHEAT
  - CARROTS
  - POTATOES
  - MELON_STEM
  - ATTACHED_MELON_STEM
  - PUMPKIN_STEM
  - ATTACHED_PUMPKIN_STEM
  - BEETROOTS